server:
  eurekaPort: 8091
  clientPort: 8010
spring:
  application:
    name: spring-cloud-ftp-server
  cloud:
    client:
      ipAddress: 10.1.1.133
eureka:  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.clientPort}
    protocol: http
    hostname: ${spring.cloud.client.ipAddress}
  client:   
    register-with-eureka: true
    fetch-registry: true   
    serviceUrl:
      defaultZone: ${eureka.instance.protocol}://${eureka.instance.hostname}:${server.eurekaPort}/eureka