server:
  eurekaPort: 8091
  port: 9100
spring:
  application:
    name: spring-cloud-ftp-server
  cloud:
    client:
      ipAddress: 10.1.1.133
eureka:  
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    protocol: http
#    hostname: ${spring.cloud.client.ipAddress}
  client:   
    register-with-eureka: true
    fetch-registry: true   
    serviceUrl:
      defaultZone: http://localhost:8091/eureka