eureka:
  client:
    #標誌為eureka服務器無需去註冊本身,默認為true
    register-with-eureka: true
    #標誌是否從eureka服務器去獲取註冊信息,默認為true
    fetch-registry: true
    #設置eureka服務器交互地址,查詢服務和註冊服務都依賴此地址,默認地址為http://localhost:8761/eureka
    serviceUrl:
      defaultZone: http://localhost:8091/eureka